package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"cerebra/apps/api/internal/graphql/generated"
	"context"
)

func (r *queryResolver) Me(ctx context.Context) (*generated.User, error) {
	user := &generated.User{
		Email: "john@example.com",
		Name:  "John Doe",
		App:   "Cerebra",
	}
	return user, nil
}

func (r *queryResolver) Events(ctx context.Context) ([]string, error) {
	events := []string{"Hackathon Kickoff", "Workshop on AI", "Closing Ceremony"}
	return events, nil
}

func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
